name: ci

on: 
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
  eslint:
    runs-on: windows-latest

    steps:
      - name: check out repo
        uses: actions/checkout@v2

      - name: set up node
        uses: actions/setup-node@v3
        with:
            node-version: '16.x'

      - name: npm install
        run: npm ci

      - name: eslint
        run: npm run lint